4 hu 002 ta 001 hacer formulario para el registro de una venta
abrilonia/Mesa-Lista-App pull request #7
Opened 2023-03-23 17:11 UTC by LucasA75

Esta hecho lo mas basico... dime si te gusta la disposicion de contenidos , que le cambiarias , donde colocarías color y si le quito alguna cosa

2023-03-23 23:04 UTC, abrilonia requested changes
el formulario debe permitir que se digiten varios productos en una venta, como está se puede registrar solo uno, el diseño está muy bien, los colores y la disposición de las cosas.

2023-03-24 19:57 UTC, LucasA75 commented
![61098bc7-2fc2-4bb8-9216-ac16e3a453ff](https://user-images.githubusercontent.com/115661399/227626363-442fefea-58b6-45a8-b87a-3d66c7e45ce6.jpg)
[](url)


Ahi le agrege que se pueda agregar los valores por javascript 🤗, me costo jajaja , el tema de la fecha es necesario ? , porque se puede adjuntar al enviar el formulario , nose , quizas por si quieres hacer un pedido para mas adelante no ? 

Quizas en vez de que dija enviar el boton tenga que decir añadir ... nose dime tu que tal

2023-03-25 19:25 UTC, abrilonia commented
Está perfecto Lucas, lo que dijiste del añadir me parece bien, y que el confirmar venta la registre y se genere un vale para imprimir y cobrarle al cliente pero eso sería en otro sprint. Gracias.

2023-03-25 21:12 UTC, LucasA75 reviewed
Cambios realizados

2023-03-25 21:12 UTC, LucasA75 commented on Formulario.html
> +        </form>
Aqui esta el cambio de nombre

2023-03-25 21:19 UTC, abrilonia approved these changes
buen trabajo Lucas

2023-03-25 21:27 UTC, merged